### PR TITLE
Rename "name" in Zone model to "id"

### LINKED ISSUE #14: Zone API returning empty 'name' column while 'id' is expected
I am using this package for reference.

Currently trying to get the Zones through this package, which works but I am not getting the 'id' column, I am getting an empty/null 'name' column. (See image below)

Your documentation @ https://www.upcloud.com/api/5-zones/#zones states that it should return an ID and description.

What is going wrong?

Image

### PR DESCRIPTION
**Pull request by Darep**
Fixes #14, but not sure if this breaks something elsewhere 🤔

### CODE REVIEW

**Comment by Cannonb4ll** [comment]
Is there an ETA when this will be merged and released?

**Comment by Darep** [comment]
It's mostly down to just testing this properly 😊 No ETA unfortunately

Any chance you could give it a shot in your project as well? That everything still works? Would be hugely appreciated!  If you're using composer, you could e.g. replace the Zone.php file in `vendor/upcloudltd/upcloud-php-api/lib/Model/Zone.php` with this one from this branch: [Zone.php](https://raw.githubusercontent.com/UpCloudLtd/upcloud-php-api/a62971cff3046bceca9517fdc80562d5f77a9190/lib/Model/Zone.php)

**Comment by Cannonb4ll** [comment]
Awesome. Just tested, works perfectly:

image

**Comment by Darep** [comment]
Great to hear, and thanks for testing! We will run some internal automated tests and hopefully those pass and we can merge this

**Comment by peter279k** [comment]
The Travis CI build is canceled. It seems to be fixed.

**Comment by Cannonb4ll** [comment]
Is there any ETA on this? I still have it hardcoded but would really like to change this.

**Comment by Darep** [comment]
Sorry for the delay! Thanks for testing this @Cannonb4ll (and others) 😊 Merging!

**Comment by Cannonb4ll** [comment]
Thank you @Darep, will there be a release published with this PR?

**Comment by Darep** [comment]
Yes! Though, not just yet! I don't have access to packagist so will have to consolidate with others and hopefully will have new release later this week :)

**Comment by Darep** [comment]
Version 1.0.3 now released :) https://packagist.org/packages/upcloudltd/upcloud-php-api

**Comment by Cannonb4ll** [comment]
@Darep Thank you, can confirm it fully working, will be updating our hardcoded code into the API call in Ploi.

**Pull request merged**
